### ISSUE TITLE
Inkscape installed with snap extension gives error: No module named inkex

### ISSUE THREAD

**Issue by NieneB** [Neon22/inkscape-jigsaw#15]
Hello I would love to use this tool!  
Running the tool throws the following error:

```Traceback (most recent call last):
  File "Lasercut-jigsaw.py", line 39, in <module>
    import inkex, simplestyle, simpletransform, cubicsuperpath
ImportError: No module named inkex
``` 
 I installed inkscape (0.92) with snap on Ubuntu 18.04. So my User extensions folder is at `/home/niene/snap/inkscape/7378/extensions` . Copying the files there gives me the extension. But it won't run. 

What can I do?

**Comment by Neon22** [comment]
I can't say for sure but it appears snap is a bundled app kind of thing. So its at least possible that the paths for the system config directory is not there.
Can I suggest you uninstall the snap app and use apt instead ?
sudo apt-get install “package-name”
I only suggest his because there are heaps of working versions of his using apt but I just don;t have any familiarity with snap.

You could also just check your path variable ?

Otherwise I'd suggest raising the issue on the snap forum because other people will run into this too with any inkscape extensions...

**Comment by NieneB** [comment]
Yes the `~/.config/inkscape/extensions` directory is not there. The inkscape `Edit > Preferences > System` show me the `~/snap/inkscape/7378/extensions`  directory. But I guess it does not find the other modules needed. 

I removed inkscape with snap and  installed again with apt-get. Now it is working :) Someone suggested me snap because that was the next hip thing to use... guess I'll stick with apt-get for a while. 

Thanks for the reply!

**Comment by Neon22** [comment]
ok closing
