### ISSUE TITLE
Separate pieces

### ISSUE THREAD

**Issue by asimov6** [Neon22/inkscape-jigsaw#4]
Hi,
When I check the "create pieces as well" checkbox I get a second set with rows and columns as separate paths, but no separate pieces. Is this intended or is it not finished yet?
Thanks

**Comment by Neon22** [comment]
The hope was that at some point the ability to do booleans would be exposed so Python and scripts could use it.
Theoretically this may be possible for Linux users using the DBUS interface but I'm a windows users and DBUS doesn't work for me.

So the checkbox exercises the code inside the existing plugin - which breaks the jigsaw into rows and columns so that a manual Boolean difference function can generate the pieces manually.

At the moment this is the best we can do. 
I've been lobbying for 8 years for Python scripting support. I expect to die before it is made available. Maybe someone will be able to fork this code when it does, and realise the intention of the script. I hope so :)

**Comment by asimov6** [comment]
Thanks, unfortunately I don't know enough about Inkscape to fully understand your answer. Hope you will live long enough to finish it ;)
